language: php
sudo: false
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
env:
- WP_VERSION=latest WP_MULTISITE=0
matrix:
  include:
  - php: 5.6
    env: WP_VERSION=3.8.16 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=3.9.14 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.0.13 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.1.13 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.2.10 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.3.6 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.4.5 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=4.5.4 WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=nightly WP_MULTISITE=0
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1
  - php: 5.2
    env: WP_VERSION=latest WP_MULTISITE=0
    dist: precise
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=0
    dist: precise
  allow_failures:
  - env: WP_VERSION=nightly WP_MULTISITE=0
before_script:
- bash tests/bin/install.sh the_social_links_test root '' localhost $WP_VERSION
- bash tests/bin/travis.sh
script:
- find . \( -name '*.php' \) -exec php -lf {} \;
- "/tmp/wordpress-tests-lib/php-codesniffer/bin/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml
  --extensions=php"
- phpunit -c phpunit.xml.dist
branches:
  only:
  - master
  - develop
notifications:
  slack:
    rooms:
      secure: aWx3/a9EbFn2RPDSQOtlpBrHeNxyrzFMx0ebIRPKSh+C9vjWVVQtp0Knzo+grbJma2hJqqOUhsonEOxga1ZAYnJ/XV1cg2zYIYxCgwpsgu7lQDRD6Yak1PrTZ9L4rIVwQpZ6hGubq2Ket7lfjdo6dKT7HybIzxFYaSkJz4pv4CL5uNdWiik8Z8C7Fl3Zg0WbX5tClDaYPj40euscGfZC8NjVCwMaDwQR8s2lOht5j52i+TVZkbi+q2GafnmsoJJmO9Z0GPe1YKILXfm1UdptUAkpoDyc/5PHmdELuAtjEpDdP0wC+1phFUJjnty64jUWDVIMUt1KRBZsprKQQj48CeYZw77CG0bHAZtImUMXut3UwY9+Hox689zjtEV54fTAhvfRbO+sl2THUvAM3X/t4cx730Da+17OM+/pT3ICqo/sWTEo27q2465na1BlphefaJWOcVzW9HFQQpg6ZJZMHa0d5NL946gjSPu/1Jss5n7d2UsxqD6MT/v+AWwfmcgEhghQnhEkMbcp/vR1MvOSYDmWL3Wuzxe7YLF2cGcOgD0W1XNgFTilH/d0Ju+/Wajo+HMBPQJYsXKlNf9BEMBDXesmKEIaxBdMP1hJ56vQZ2n+vWMzf7X6F1ExMXgH5Ofe5Hmt4nUk0zL/XLgXTMWbzd6dyzsf5TwiwEg4Q/ytkTs=
